### ISSUE TITLE
Docuent how to switch toolchains.

### ISSUE THREAD

**Issue by lievenvanderheide** [AndrewGaspar/corrosion#43]
I tried adding 

`set(RUSTUP_TOOLCHAIN "nightly-x86_64-unknown-linux-gnu")`

to my CMakeLists.txt file, but that doesn't seem to have any effect, it's still using the stable toolchain.

**Comment by AndrewGaspar** [comment]
I actually just fixed a bug related to this in a WIP branch - basically, changing `RUSTUP_TOOLCHAIN` doesn't cause Rust to re-query the toolchain. I fixed it so that if the `RUSTUP_TOOLCHAIN` variable changes, then the toolchain will be re-queried.

If you create a new configuration directory, does nightly get selected?

**Comment by lievenvanderheide** [comment]
Things work fine if I create a new config directory indeed, so the problem was most likely the bug you've already fixed in your WIP branch.

Thanks for the help.

**Comment by AndrewGaspar** [comment]
Excellent. I'll close this issue once I've merged that branch and added some documentation for the option.
